name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: (Optional) Skip macro validation globally for this runner
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: ðŸ” Create Secrets.xcconfig file
        env:
          XCCONFIG_SECRETS: ${{ secrets.XCCONFIG_SECRETS }}
        run: |
          echo "$XCCONFIG_SECRETS" > Marvelous/Marvelous-iOS/Marvelous-iOS/Config/Secrets.xcconfig

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -project Marvelous-iOS/Marvelous-iOS.xcodeproj \
            -scheme Marvelous-iOS \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

      - name: Run tests
        run: |
          xcodebuild test-without-building \
            -project Marvelous-iOS/Marvelous-iOS.xcodeproj \
            -scheme Marvelous-iOS \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -skipMacroValidation
